# Generated by Django 4.2 on 2023-04-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(default=0, verbose_name='ID в Telegram')),
                ('name', models.CharField(max_length=255, verbose_name='Ник в Telegram')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
            ],
            options={
                'verbose_name': 'Клиент в TG',
                'verbose_name_plural': 'Клиенты в TG',
            },
        ),
    ]
