# Generated by Django 4.1.7 on 2023-03-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='offer_photo', verbose_name='Файл с фото')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена')),
                ('house_area', models.PositiveIntegerField(verbose_name='Площадь дома')),
                ('territory_area', models.PositiveIntegerField(verbose_name='Площадь земли')),
                ('territory_area_points', models.CharField(choices=[('м²', 'м²'), ('км²', 'км²'), ('сотка', 'сотка'), ('сотки', 'сотки'), ('а', 'а'), ('га', 'га')], max_length=255, verbose_name='Единицы измерения площади земли')),
                ('room_count', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('exit_to_the_terrace', models.BooleanField(verbose_name='Выход на террасу')),
                ('deadline', models.PositiveIntegerField(verbose_name='Сроки работ')),
                ('deadline_points', models.CharField(choices=[('час', 'час'), ('часа', 'часа'), ('часов', 'часов'), ('день', 'день'), ('дня', 'дня'), ('дней', 'дней'), ('неделю', 'неделю'), ('недели', 'недели'), ('недель', 'недель'), ('месяц', 'месяц'), ('месяца', 'месяца'), ('месяцев', 'месяцев'), ('год', 'год'), ('года', 'года'), ('лет', 'лет')], max_length=255, verbose_name='Единицы измерения сроков работ')),
                ('finishing', models.CharField(choices=[('Черновая', 'Черновая'), ('Предчистовая', 'Предчистовая'), ('Чистовая', 'Чистовая')], max_length=255, verbose_name='Отделка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ManyToManyField(to='offers.offerphoto', verbose_name='Фото')),
            ],
        ),
    ]
