# Generated by Django 4.1.7 on 2023-03-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPhotoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='offer_photo_main', verbose_name='Файл с фото')),
            ],
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AddField(
            model_name='offer',
            name='floor_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество этажей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='main_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offerphotomain', verbose_name='Главное фото'),
        ),
    ]
