# Generated by Django 4.1.7 on 2023-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offerphotomain_alter_offer_options_offer_floor_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='territory_area_points',
            field=models.CharField(choices=[('м²', 'м²'), ('км²', 'км²'), ('сот.', 'сот.'), ('а', 'а'), ('га', 'га')], max_length=255, verbose_name='Единицы измерения площади земли'),
        ),
    ]
