# Generated by Django 4.1.7 on 2023-03-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_territory_area_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPhotoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='offer_photo_plan', verbose_name='Файл с фото')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='plan_photo',
            field=models.ManyToManyField(to='offers.offerphotoplan', verbose_name='План дома'),
        ),
    ]
