# Generated by Django 4.1.7 on 2023-03-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offerphotoplan_offer_plan_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полный адрес'),
        ),
    ]
