# Generated by Django 4.2 on 2023-04-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
