# Generated by Django 4.2 on 2023-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_request_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='deadline',
            field=models.FloatField(verbose_name='Сроки работ'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='house_area',
            field=models.FloatField(verbose_name='Площадь дома (м²)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='territory_area',
            field=models.FloatField(verbose_name='Площадь земли'),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
